version: '3.1'

name: 'soil-sampling'
services:
  mongodb:
    image: 'mongo:6.0.4'
    container_name: 'mongo-dev'
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=replicaset
      - MONGODB_EXTRA_FLAGS=--bind_ip_all
